# Name of the GitHub Actions workflow
name: Update Sing-Box Subscription

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow on a schedule
  schedule:
    # This runs the job at minute 10 past every hour.
    - cron: '10 * * * *'

# Granting write permissions to the workflow
permissions:
  contents: write

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installs the necessary Python packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4. Runs the Python script to generate the subscription files
      - name: Generate new subscription files
        run: python generate_subs.py

      # 5. Commits the changes back to your repository
      - name: Commit and push changes
        run: |
          # Configure git with the bot's name and email
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Add all new and changed files to the staging area
          git add .
          
          # Commit the changes if there are any, and push to the main branch
          # The "[skip ci]" message prevents this commit from triggering another workflow run.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update subscription files [skip ci]"; git push)
          
          echo "Workflow finished. Changes (if any) have been pushed."
